ame: Practice GitHub Action

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Run practice test
        run: echo "GitHub Actions practice is successful!"
